services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --describe"]
      interval: 2s
      timeout: 2s
      retries: 15

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181

  postgres:
    container_name: postgres
    image: postgres
    ports:
    - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 15
  
  notes: 
    container_name: notes
    image: notes
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - SECRET_STRING=19b903688f1152fbf156c4f2edb08b42529f483ac10eeeaec861280e70bb9192
    depends_on:
      postgres:
        condition: service_healthy

  authorization: 
    container_name: authorization
    image: authorization
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=topic1
      - SECRET_STRING=19b903688f1152fbf156c4f2edb08b42529f483ac10eeeaec861280e70bb9192
    depends_on:
      postgres:
        condition: service_healthy

  mailer: 
    container_name: mailer
    image: mailer
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      kafka:
        condition: service_healthy