services:
  server-dev:
    restart: unless-stopped
    image: example-back-dev:latest
    env_file:
      - .env.dev
    volumes:
      - ./media-dev:/app/media

  server-prod:
    restart: unless-stopped
    image: example-back-prod:latest
    env_file:
      - .env.prod
    volumes:
      - ./media-prod:/app/media

networks:
  default:
    external: true
    name: z-net
